
spring:
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost:8888"
server:
    port: 8081
zipkin:
    base-url: "http://localhost:9411"
sleuth:
    sampler:
      probability: 1.0