spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shubhanginaik/microservice-config-server.git
          search-paths: config-server
          clone-on-start: true
server:
  port: 8888